use_frameworks!

platform :ios, '8.0'

target 'LLNetWorking_Example' do
  pod 'LLNetWorking', :path => '../'

  target 'LLNetWorking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
